FROM apache/airflow:2.9.1

USER root

# Install OpenJDK-17
RUN apt update &&  \
    apt-get install -y openjdk-17-jdk && apt-get install -y procps && \
    apt-get install -y ant && \
    apt-get clean;
    
RUN apt-get install -y wget && \
    wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc && \
    chmod +x /usr/local/bin/mc

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
ENV PATH=$PATH:/opt/spark/bin


USER airflow

RUN pip install apache-airflow-providers-apache-spark





